from .baselines.h2o.modify_llama import make_llama_attention_h2o as make_llama_attention_h2o
from .baselines.topk.modify_llama import make_llama_attention_top_k as make_llama_attention_top_k
from .sparhat.modify_llama import make_llama_attention_sparhat as make_llama_attention_sparhat
from .sparhat.cache_utils import SparHatCache